messages:
  enchant-not-compatible: "&7[&c&l!&7] &cThat enchant is not compatible with that item!"
  not-enough-exp: "&7[&c&l!&7] &cYou do not have enough experience to buy that enchant!"
  not-enough-money: "&7[&c&l!&7] &cYou do not have enough money to buy that enchant!"
  pickpocket-money-was-stolen: "&7[&a&l!&7] &c{player} stole ${amount} from you!"
  pickpocket-stole-money: "&7[&a&l!&7] &aYou stole ${amount} from {player}!"
enchanter-menu:
  menu-title: "&c&lEnchanter"
  canAffordColor: "&a"
  cannotAffordColor: "&c"
  tools:
    # Set prices to -1 to disable
    exp-price: 100
    dollar-price: -1
    item:
      material: NETHER_STAR
      data: 0
      name: "&a&lTools Enchants"
      lore:
        - "&7Price: 100exp"
        - "&7Current Exp: {hasEnoughExpColor}{currentExp}"
        - "&r"
        - "&7&lAvailable Enchants:"
        - "&7-&6 Mobcoin Luck"
        - "&7-&6 Haste"
        - "&7-&6 Smelter"
        - "&7-&6 Experience"
        - "&7-&6 Obsidian Destroyer"
  armor:
    exp-price: -1
    dollar-price: 200
    item:
      material: NETHER_STAR
      data: 0
      name: "&b&lArmor Enchants"
      lore:
        - "&7Price: $200"
        - "&7Current Bal: {hasEnoughMoneyColor}${currentMoney}"
        - "&r"
        - "&7&lAvailable Enchants:"
        - "&7-&6 Lumination"
        - "&7-&6 Implants"
        - "&7-&6 Health Boost"
        - "&7-&6 Regeneration"
        - "&7-&6 Fire Immunity"
        - "&7-&6 Ninja"
        - "&7-&6 Jump"
        - "&7-&6 Speed"
  sword:
    exp-price: 200
    dollar-price: 200
    item:
      material: NETHER_STAR
      data: 0
      name: "&c&lSword Enchants"
      lore:
        - "&7Price: 200exp & $200"
        - "&7Current Exp: {hasEnoughExpColor}{currentExp}"
        - "&7Current Bal: {hasEnoughMoneyColor}${currentMoney}"
        - "&r"
        - "&7&lAvailable Enchants:"
        - "&7-&6 Strength"
        - "&7-&6 Damage"
        - "&7-&6 Pick Pocket"
        - "&7-&6 Inquisitive"
        - "&7-&6 Freeze"
enchant-scrolls:
  tools:
    #color must be: WHITE, SILVER, GRAY, BLACK, RED, MAROON, YELLOW, OLIVE, LIME, GREEN, AQUA, TEAL, BLUE, NAVY, FUCHSIA, PURPLE, ORANGE,
    color: GREEN
    name: "&a&l{name} {level} Scroll"
    lore:
      - "&7Enchant Compatibility: &lTools"
      - "&6Place onto compatible item to add enchant"
  armor:
    #color must be: WHITE, SILVER, GRAY, BLACK, RED, MAROON, YELLOW, OLIVE, LIME, GREEN, AQUA, TEAL, BLUE, NAVY, FUCHSIA, PURPLE, ORANGE,
    color: BLUE
    name: "&b&l{name} {level} Scroll"
    lore:
      - "&7Enchant Compatibility: &lArmor"
      - "&6Place onto compatible item to add enchant"
  sword:
    #color must be: WHITE, SILVER, GRAY, BLACK, RED, MAROON, YELLOW, OLIVE, LIME, GREEN, AQUA, TEAL, BLUE, NAVY, FUCHSIA, PURPLE, ORANGE,
    color: RED
    name: "&c&l{name} {level} Scroll"
    lore:
      - "&7Enchant Compatibility: &lSwords"
      - "&6Place onto compatible item to add enchant"
enchant-chances:
  #each category must total to 100 (if its not 100 there is a chance a player gets nothing)
  tools:
    mobcoin-luck: 20
    haste: 20
    smelter: 20
    experience: 20
    obsidian-destroyer: 20
  armor:
    lumination: 12.5
    implants: 12.5
    health-boost: 12.5
    regeneration: 12.5
    fire-immunity: 12.5
    ninja: 12.5
    jump: 12.5
    speed: 12.5
  sword:
    strength: 20
    damage: 20
    pick-pocket: 20
    inquisitive: 20
    freeze: 20
enchant-level-chances:
  #each enchant must total to 100 (if its not 100 there is a chance a player gets nothing)
  mobcoin-luck:
    1: 25
    2: 25
    3: 25
    4: 25
  haste:
    1: 34
    2: 33
    3: 33
  smelter:
    1: 100
  experience:
    1: 25
    2: 25
    3: 25
    4: 25
  obsidian-destroyer:
    1: 100
  lumination:
    1: 100
  implants:
    1: 50
    2: 50
  health-boost:
    1: 50
    2: 50
  regeneration:
    1: 50
    2: 50
  fire-immunity:
    1: 100
  ninja:
    1: 100
  jump:
    1: 50
    2: 50
  speed:
    1: 50
    2: 50
  strength:
    1: 100
  damage:
    1: 50
    2: 50
  pick-pocket:
    1: 50
    2: 50
  inquisitive:
    1: 34
    2: 33
    3: 33
  freeze:
    1: 50
    2: 50
enchants:
  lore-format: "&b{name} {level}"
  levels:
    1: "I"
    2: "II"
    3: "III"
    4: "IV"
    5: "V"
  smelter:
    IRON_ORE: "IRON_INGOT"
    GOLD_ORE: "GOLD_INGOT"
    QUARTZ_ORE: "QUARTZ"
    SAND: "GLASS"
    COBBLESTONE: "STONE"
    NETHERRACK: "NETHER_BRICK_ITEM"
  damage:
    1:
      chance: 20
      amount-of-hearts: 0.5
    2:
      chance: 50
      amount-of-hearts: 1
  experience:
    1:
      chance: 20
      exp-multiplier: 2.5
    2:
      chance: 30
      exp-multiplier: 3
    3:
      chance: 40
      exp-multiplier: 4
    4:
      chance: 50
      exp-multiplier: 5.5
  mobcoin-luck:
    1:
      chance: 20
      amt-of-mobcoins: 1
    2:
      chance: 25
      amt-of-mobcoins: 2
    3:
      chance: 30
      amt-of-mobcoins: 3
    4:
      chance: 40
      amt-of-mobcoins: 4
  pick-pocket:
    1:
      chance: 20
      percent-to-steal: 5
    2:
      chance: 40
      percent-to-steal: 7.5
  inquisitive:
    1:
      chance: 20
      exp-to-add: 200
    2:
      chance: 30
      exp-to-add: 300
    3:
      chance: 40
      exp-to-add: 400
  freeze:
    1:
      chance: 20
      duration-in-secs: 2
    2:
      chance: 30
      duration-in-secs: 4
  potion-levels:
    lumination:
      1: 1
    implants:
      1: 1d
      2: 2
    health-boost:
      1: 5
      2: 10
    regeneration:
      1: 1
      2: 2
    fire-immunity:
      1: 1
    ninja:
      1: 2
    jump:
      1: 2
      2: 4
    speed:
      1: 2
      2: 3
    haste:
      1: 1
      2: 3
      3: 5
    strength:
      1: 2
right-clickable-blocks-dont-armor-mount:
  - 'FURNACE'
  - 'CHEST'
  - 'TRAPPED_CHEST'
  - 'BEACON'
  - 'DISPENSER'
  - 'DROPPER'
  - 'HOPPER'
  - 'WORKBENCH'
  - 'ENCHANTMENT_TABLE'
  - 'ENDER_CHEST'
  - 'ANVIL'
  - 'BED_BLOCK'
  - 'FENCE_GATE'
  - 'SPRUCE_FENCE_GATE'
  - 'BIRCH_FENCE_GATE'
  - 'ACACIA_FENCE_GATE'
  - 'JUNGLE_FENCE_GATE'
  - 'DARK_OAK_FENCE_GATE'
  - 'IRON_DOOR_BLOCK'
  - 'WOODEN_DOOR'
  - 'SPRUCE_DOOR'
  - 'BIRCH_DOOR'
  - 'JUNGLE_DOOR'
  - 'ACACIA_DOOR'
  - 'DARK_OAK_DOOR'
  - 'WOOD_BUTTON'
  - 'STONE_BUTTON'
  - 'TRAP_DOOR'
  - 'IRON_TRAPDOOR'
  - 'DIODE_BLOCK_OFF'
  - 'DIODE_BLOCK_ON'
  - 'REDSTONE_COMPARATOR_OFF'
  - 'REDSTONE_COMPARATOR_ON'
  - 'FENCE'
  - 'SPRUCE_FENCE'
  - 'BIRCH_FENCE'
  - 'JUNGLE_FENCE'
  - 'DARK_OAK_FENCE'
  - 'ACACIA_FENCE'
  - 'NETHER_FENCE'
  - 'BREWING_STAND'
  - 'CAULDRON'
  - 'SIGN_POST'
  - 'WALL_SIGN'
  - 'SIGN'
  - 'LEVER'